#include<stdio.h>
#define size 200

int main()
{
    char sum[size],a[size],b[size];
    int i,j,k,c,s,len;
    while(1)
    {
        scanf("%s",a);
        if(strcmp(a,"0")==0)
        {
            printf("0\n");
            break;
        }
        scanf("%s",b);
        if(strcmp(b,"0")==0)
        {
            printf("%s",a);
            break;
        }
        for(i=0;i<size;i++)
            sum[i]=48;
        i=size-1;
        c=0;
        j=strlen(a)-1;
        k=strlen(b)-1;
        while(j>=0&&k>=0)
        {
            s=(a[j]-48)+(b[k]-48)+c;
            c=s/10;
            sum[i]=s%10+48;
            i--;
            j--;
            k--;
        }
        while(j>=0)
        {
            s=(a[j]-48)+c;
            c=s/10;
            sum[i]=s%10+48;
            j--;
            i--;
        }
        while(k>=0)
        {
            s=(b[k]-48)+c;
            c=s/10;
            sum[i]=s%10+48;
            k--;
            i--;
        }
        while(c)
        {
            sum[i]=c%10+48;
            c/=10;
            i--;
        }
        len=i+1;
        while(1)
        {
            scanf("%s",b);
            if(strcmp(b,"0")==0)
                break;
            j=strlen(b)-1;
            i=size-1;
            c=0;
            while(i>=len&&j>=0)
            {
                s=(sum[i]-48)+(b[j]-48)+c;
                c=s/10;
                sum[i]=s%10+48;
                i--;
                j--;
            }
            while(j>=0)
            {
                s=(b[j]-48)+c;
                c=s/10;
                sum[i]=s%10+48;
                i--;
                j--;
            }
            while(i>=len)
            {
                s=(sum[i]-48)+c;
                c=s/10;
                sum[i]=s%10+48;
                i--;
            }
            while(c)
            {
                s=(sum[i]-48)+c;
                c=s/10;
                sum[i]=s%10+48;
                i--;
            }
            len=i+1;
        }
        break;
    }
    for(j=len;j<size;j++)
        printf("%c",sum[j]);
    return 0;
}
