#include<stdio.h>

int main()
{
    char a[81],b[81];
    int t,m,n,c,s,i,cnt=0;
    scanf("%d",&t);
    while(t--)
    {
        scanf("%s%s",a,b);
        cnt++;
        printf("%d ",cnt);
        m=strlen(a)-1;
        n=strlen(b)-1;
        c=s=0;
        if(m>n)
        {
            while(n>=0)
            {
                s=a[m]+b[n]+c-96;
                c=s/2;
                a[m]=(s%2)+48;
                n--;
                m--;
            }
            while(m>=0&&c)
            {
                s=a[m]+c-48;
                c=s/2;
                a[m]=(s%2)+48;
                m--;
            }
            if(c)
            {
                printf("1");
                for(i=0;i<strlen(a);i++)
                    printf("%c",a[i]);
            }
            else
            {
                for(i=0;a[i]=='0';i++);
                if(i==strlen(a))
                    printf("0");
                else
                    for(;i<strlen(a);i++)
                        printf("%c",a[i]);
            }
        }
        else if(m<n)
        {
            while(m>=0)
            {
                s=a[m]+b[n]+c-96;
                c=s/2;
                b[n]=(s%2)+48;
                n--;
                m--;
            }
            while(n>=0&&c)
            {
                s=b[n]+c-48;
                c=s/2;
                b[n]=(s%2)+48;
                n--;
            }
            if(c)
            {
                printf("1");
                for(i=0;i<strlen(b);i++)
                    printf("%c",b[i]);
            }
            else
            {
                for(i=0;b[i]=='0';i++);
                if(i==strlen(b))
                    printf("0");
                else
                    for(;i<strlen(b);i++)
                        printf("%c",b[i]);
            }
        }
        else
        {
            while(n>=0)
            {
                s=a[m]+b[n]+c-96;
                c=s/2;
                a[m]=(s%2)+48;
                n--;
                m--;
            }
            if(c)
            {
                printf("1");
                for(i=0;i<strlen(a);i++)
                    printf("%c",a[i]);
            }
            else
            {
                for(i=0;a[i]=='0';i++);
                if(i==strlen(a))
                    printf("0");
                else
                    for(;i<strlen(a);i++)
                        printf("%c",a[i]);
            }
        }
        printf("\n");
    }
    return 0;
}
